### ISSUE TITLE
upgrade project 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/hacktoberfest2023#13]
update project with real world project. adding details

**Comment by Kd-Here** [comment]
Hey @devvsakib i am beginner for HACKTOBERFEST 
Can you guide me what to merge ?

**Comment by devvsakib** [comment]
completed #14

**Comment by devvsakib** [comment]
please read this carefully https://github.com/devvsakib/hacktoberfest2023/blob/main/CONTRIBUTING.md

**Comment by devvsakib** [comment]
@Kd-Here  please read this carefully https://github.com/devvsakib/hacktoberfest2023/blob/main/CONTRIBUTING.md
