### ISSUE TITLE
install nextjs

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/Hacktoberfest2023#5]
very simple task, just install next js and make a PR for your first #hacktoberfest pr

**Comment by vd89** [comment]
Hello @devvsakib  

would like to contribute to the same 
- need to know a few details 
- can you tell me what would be used for next js  in terms of language like [typescript, javascript]

**Comment by devvsakib** [comment]
javascript, just install nextjs with tailwind and make pr, make sure to use separate branch @vd89

**Comment by sulavghimiree** [comment]
As I am interested in next.js. I will like to do it. Assign it to me

**Comment by vd89** [comment]
Thanks for the Details @devvsakib  
will do the changes and raise the pr

**Comment by devvsakib** [comment]
assigned @vd89

**Comment by devvsakib** [comment]
Completed #8 

Let me know if your PR counted in Hacktoberfest☑️
